--- #YAML:1.0
name:               XML-Debian-ENetInterfaces
version:            0.03
abstract:           Work with Debian's /etc/network/interfaces in XML.
author:
    - Michael Mestnik <cheako+cpan@mikemestnik.net>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:           0
    XML::LibXML:          0
    XML::Parser::PerlSAX:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
